name: cpuinfo_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_auth: ^4.0.0
  google_sign_in: ^6.2.1
  adaptive_theme: ^3.6.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
      - assets/img/
      
