// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7MzI48QUBf5lBWswybM4r5Pu0cL6DPLk',
    appId: '1:1011687248688:web:c6d5998029927997266ef5',
    messagingSenderId: '1011687248688',
    projectId: 'cpu-info-ed142',
    authDomain: 'cpu-info-ed142.firebaseapp.com',
    storageBucket: 'cpu-info-ed142.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGiTyHPDXf2LYvK-IMnU5w8BQHBwIwuVQ',
    appId: '1:1011687248688:android:a3a5e0e5e91d092a266ef5',
    messagingSenderId: '1011687248688',
    projectId: 'cpu-info-ed142',
    storageBucket: 'cpu-info-ed142.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7MzI48QUBf5lBWswybM4r5Pu0cL6DPLk',
    appId: '1:1011687248688:web:d9d13213fc364f7c266ef5',
    messagingSenderId: '1011687248688',
    projectId: 'cpu-info-ed142',
    authDomain: 'cpu-info-ed142.firebaseapp.com',
    storageBucket: 'cpu-info-ed142.appspot.com',
  );

}